import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../config/environment.dart';

/// Message tuple used for the chat request's conversation history.
class AiHistoryEntry {
  final String role;
  final String content;

  const AiHistoryEntry({required this.role, required this.content});

  Map<String, dynamic> toJson() => {'role': role, 'content': content};
}

/// Chat response from the Rever AI backend.
class AiChatResult {
  final String reply;
  final List<GroundingSource> groundingSources;

  const AiChatResult({
    required this.reply,
    this.groundingSources = const [],
  });

  bool get hasGrounding => groundingSources.isNotEmpty;
}

/// A learning-idea card generated by the AI backend.
class AiGeneratedCard {
  final String takeaway;
  final String body;
  final String type; // 'overview' | 'idea' | 'takeaway'

  const AiGeneratedCard({
    required this.takeaway,
    required this.body,
    this.type = 'idea',
  });

  factory AiGeneratedCard.fromJson(Map<String, dynamic> json) => AiGeneratedCard(
        takeaway: json['takeaway'] as String? ?? '',
        body: json['body'] as String? ?? '',
        type: json['type'] as String? ?? 'idea',
      );
}

class GroundingSource {
  final String title;
  final String url;
  final String snippet;

  const GroundingSource({
    required this.title,
    this.url = '',
    this.snippet = '',
  });

  factory GroundingSource.fromJson(Map<String, dynamic> json) =>
      GroundingSource(
        title: json['title'] as String? ?? '',
        url: json['url'] as String? ?? '',
        snippet: json['snippet'] as String? ?? '',
      );
}

/// Thin client for the Rever AI FastAPI service.
///
/// Purely additive: if the backend is unreachable, callers fall back to
/// local placeholder content, so the UI never blocks in dev.
class AiApiService {
  final Dio _dio;
  bool? _available;

  AiApiService({Dio? dio})
      : _dio = dio ??
            Dio(BaseOptions(
              baseUrl: AppEnvironment.aiBaseUrl,
              connectTimeout: const Duration(seconds: 3),
              receiveTimeout: const Duration(seconds: 30),
            ));

  /// Whether the AI backend is reachable. Cached per session so we don't
  /// hammer the network with repeated failing probes.
  Future<bool> isAvailable() async {
    if (_available != null) return _available!;
    try {
      final resp = await _dio.get<Map<String, dynamic>>('/health');
      _available = resp.statusCode == 200;
    } catch (_) {
      _available = false;
    }
    return _available!;
  }

  /// Generates learning-idea cards from a source text via the AI backend.
  ///
  /// Throws on network/HTTP failure — callers should catch and fall back.
  Future<List<AiGeneratedCard>> generateCards({
    required String title,
    required String sourceText,
  }) async {
    final response = await _dio.post<Map<String, dynamic>>(
      '/ai/generate/card',
      data: {'title': title, 'source_text': sourceText},
    );
    final data = response.data ?? const <String, dynamic>{};
    final cards = (data['cards'] as List? ?? const [])
        .whereType<Map<String, dynamic>>()
        .map(AiGeneratedCard.fromJson)
        .toList();
    return cards;
  }

  /// Sends a chat message to the AI Tutor endpoint.
  ///
  /// Throws on network/HTTP failure — callers should catch and fall back.
  Future<AiChatResult> chat({
    required String message,
    String mode = 'explain',
    String? conceptId,
    List<AiHistoryEntry> history = const [],
  }) async {
    final response = await _dio.post<Map<String, dynamic>>(
      '/ai/chat',
      data: {
        'message': message,
        'mode': mode,
        'concept_id': ?conceptId,
        'conversation_history': history.map((e) => e.toJson()).toList(),
      },
    );
    final data = response.data ?? const <String, dynamic>{};
    final sources = (data['grounding_sources'] as List? ?? const [])
        .whereType<Map<String, dynamic>>()
        .map(GroundingSource.fromJson)
        .toList();
    return AiChatResult(
      reply: data['reply'] as String? ?? '',
      groundingSources: sources,
    );
  }
}

final aiApiServiceProvider = Provider<AiApiService>((ref) {
  return AiApiService();
});